import Model from "./server/Organization";
/**
 * Copyright SimplyJargon
 * Created by ssaboo .

 */

export default class Organization extends Model {
    constructor(props) {
        super(props);
    }

    getAvatar() {
        const avatar = super.getAvatar();
        if (!avatar) return "/img/org.jpg";
        return avatar;
    }
}
// Were not getting generated by swagger
Organization.hasOne = Organization.hasOne.concat([
    {
        name: "parent",
        model: "Organization"
    },
    {
        name: "root",
        model: "Organization"
    },
    {
        name: "cover",
        model: "Upload"
    }
]);
