import Model from "./server/Role";
/**
 * Copyright SimplyJargon
 * Created by ssaboo .

 */

export default class Role extends Model {
    constructor(props) {
        super(props);
    }
}

// Were not getting generated by swagger
Role.hasOne = Role.hasOne.concat([
    {
        name: "organization",
        model: "Organization"
    }
]);
