export const APPEND_LIKE = "APPEND_LIKE";
export const CHANGE_ACTIVE_PLAYLIST = "CHANGE_ACTIVE_PLAYLIST";
export const CHANGE_ACTIVE_SONG_ID = "CHANGE_ACTIVE_SONG_ID";
export const CHANGE_ACTIVE_USER_ID = "CHANGE_ACTIVE_USER_ID";
export const CHANGE_CURRENT_TIME = "CHANGE_CURRENT_TIME";
export const CHANGE_IS_MOBILE = "CHANGE_IS_MOBILE";
export const CHANGE_MODAL = "CHANGE_MODAL";
export const CHANGE_PATH = "CHANGE_PATH";
export const CHANGE_PLAYING_SONG = "CHANGE_PLAYING_SONG";
export const CHANGE_SELECTED_PLAYLISTS = "CHANGE_SELECTED_PLAYLISTS";
export const CHANGE_WIDTH_AND_HEIGHT = "CHANGE_WIDTH_AND_HEIGHT";
export const PLAY_SONG = "PLAY_SONG";
export const RECEIVE_ACCESS_TOKEN = "RECEIVE_ACCESS_TOKEN";
export const RECEIVE_AUTHED_FOLLOWINGS = "RECEIVE_AUTHED_FOLLOWINGS";
export const RECEIVE_AUTHED_PLAYLISTS = "RECEIVE_AUTHED_PLAYLISTS";
export const RECEIVE_AUTHED_USER = "RECEIVE_AUTHED_USER";
export const RECEIVE_LIKES = "RECEIVE_LIKES";

export const RECEIVE_SONG = "RECEIVE_SONG";
export const RECEIVE_SONG_COMMENTS = "RECEIVE_SONG_COMMENTS";
export const RECEIVE_SONGS = "RECEIVE_SONGS";
export const RECEIVE_NEW_STREAM_SONGS = "RECEIVE_NEW_STREAM_SONGS";
export const RECEIVE_USER = "RECEIVE_USER";
export const RECEIVE_USER_FOLLOWINGS = "RECEIVE_USER_FOLLOWINGS";
export const RECEIVE_USER_PROFILES = "RECEIVE_USER_PROFILES";
export const REMOVE_UNLIKED_SONGS = "REMOVE_UNLIKED_SONGS";
export const RESET_AUTHED = "RESET_AUTHED";
export const REQUEST_SONG = "REQUEST_SONG";
export const REQUEST_SONGS = "REQUEST_SONGS";
export const REQUEST_USER = "REQUEST_USER";
export const SET_FOLLOWING = "SET_FOLLOWING";
export const SET_LIKE = "SET_LIKE";
export const TOGGLE_IS_PLAYING = "TOGGLE_IS_PLAYING";
export const UNSHIFT_NEW_STREAM_SONGS = "UNSHIFT_NEW_STREAM_SONGS";

export const RECEIVE_PROPERTIES = "RECEIVE_PROPERTIES";
export const REMOVE_PROPERTIES = "REMOVE_PROPERTIES";
export const REQUEST_PROPERTIES = "REQUEST_PROPERTIES";
export const REMOVE_UNLIKED_PROPERTIES = "REMOVE_UNLIKED_PROPERTIES";

export const RECEIVE_ERRORS = "RECEIVE_ERRORS";

export const RECEIVE_TYPES = "RECEIVE_TYPES";
export const REQUEST_TYPES = "REQUEST_TYPES";

export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

/*
export const RECEIVE_CART = 'RECEIVE_CART';
export const REQUEST_CART= 'REQUEST_CART';
export const RECEIVE_ITEM_CART= 'RECEIVE_ITEM_CART';
export const DELETE_ITEM_CART= 'DELETE_ITEM_CART';
*/

export const RECEIVE_EDITOR = "RECEIVE_EDITOR";
export const REQUEST_EDITOR = "REQUEST_EDITOR";
export const RECEIVE_ITEM_EDITOR = "RECEIVE_ITEM_EDITOR";
export const DELETE_ITEM_EDITOR = "DELETE_ITEM_EDITOR";
export const SELECT_PORTFOLIO_EDITOR = "SELECT_PORTFOLIO_EDITOR";

export const RECEIVE_LOCALE = "RECEIVE_LOCALE";
export const RECEIVE_MESSAGES = "RECEIVE_MESSAGES";
